<div class="row">
	<div class="col s12 center">
		<div class="card-panel teal lighten-2 z-depth-2">
			<span class="grey-text text-lighten-4">
				<h6>Pagina de Inicio prueba de habilidad</h6>
			</span>
		</div>
	</div>
</div>

<div class="row">
	<div class="col s12 center">
		<a href="/index/card/" class="mdl-button mdl-button--raised mdl-button--colored">
			Consumo API con Card
		</a>
	</div>
</div>

<div class="row">
	<div class="col s12 center">
		<a href="/tabla/" class="mdl-button mdl-button--raised mdl-button--colored">
			Consumo API con DataTables
		</a>
	</div>
</div>