<style type="text/css" media="screen">
    .imgStyl {
        display: flex;
        -webkit-box-pack: center;
        justify-content: center;
        -webkit-box-align: center;
        align-items: center;
        min-height: calc(50vh - 60px);
        padding: 1rem 0px;
        background: rgb(32, 35, 41);
    }
</style>

<div class="row">
		<div class="col s10 center">
			<div class="card-panel teal lighten-2 z-depth-2">
				<span class="grey-text text-lighten-4">
					<h6>
						Consumo API con Card
					</h6>
				</span>
			</div>
		</div>
		<div class="col s2 center">
			<div class="card-panel teal lighten-2 z-depth-2">
				<span class="grey-text text-lighten-4">
						<a href="/index/" class="mdl-button mdl-button--raised mdl-button--colored">Inicio</a>
				</span>
			</div>
		</div>
</div>
<div class="row">
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1 center">
		<?php echo Phalcon\Tag::linkTo(array($linkLeft, 'keyboard_arrow_left', 'class' => 'material-icons'));?>
	</div>
	<div class="col s2 center">
		<?php echo $paginaActual;?>
	</div>
	<div class="col s1 center">
		<?php echo Phalcon\Tag::linkTo(array($linkRight, 'keyboard_arrow_right', 'class' => 'material-icons'));?>
	</div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
</div>
<div class="divider"></div>
<?php 
/**
 * Inicialzo varibales de control
 */
$c = 0; 
$fin = 0;
$sNum = 3; 
$cont = 4;
$resta = 0;

/**
 * Comienza el recorrido del arreglo obtenido de la API
 */
for ($i=0; $i < $cantRegistros; $i++) {
	$print = 0;
	$resta = $cantRegistros - $i - $c;
	if ($c == 0 && $print ==0){
		$c = 2;
		$print = 1;
		echo "<div class=\"row\">";
		if ($resta >= 4){
			echo "<div class=\"col s".$sNum." center\">";
			?>
			<div class="card blue-grey darken-1">
				<div class="card-image">
					<img src="<?php echo $jsonObjet->results[$i]->image ?>" alt="" class="responsive-img imgStyl">
					
				</div>
				<div class="card-content white-text">
					<span class="card-title flow-text">
						<h6><?php echo $jsonObjet->results[$i]->name ?></h6>
					</span>
					<p><h8><?php echo substr($jsonObjet->results[$i]->created,0,10); ?></h8></p>
				</div>
			</div>
			<?php
			echo "</div>";
		}else{
			if ($fin == 0){
				$fin = 1;
				switch ($resta) {
				    case 3: $sNum = 4; $cont = 3; break;
				    case 2: $sNum = 6; $cont = 2; break;
				    case 1: $sNum = 12; $cont = 1; break;
					}	
			}
			echo "<div class=\"col s".$sNum." center\">";
			?>
			<div class="card blue-grey darken-1">
				<div class="card-image">
					<img src="<?php echo $jsonObjet->results[$i]->image ?>" alt="" class="responsive-img imgStyl">
				</div>
				<div class="card-content white-text">
					<span class="card-title flow-text">
						<h6><?php echo $jsonObjet->results[$i]->name ?></h6>
					</span>
					<p><h8><?php echo substr($jsonObjet->results[$i]->created,0,10); ?></h8></p>
				</div>
			</div>
			<?php
			echo "</div>";
		}
	}

	if ($c < $cont && $print ==0){
			$c = $c + 1;
			$print = 1;
			echo "<div class=\"col s".$sNum." center\">";
			?>
			<div class="card blue-grey darken-1">
				<div class="card-image">
					<img src="<?php echo $jsonObjet->results[$i]->image ?>" alt="" class="responsive-img imgStyl">
				</div>
				<div class="card-content white-text">
					<span class="card-title flow-text">
						<h6><?php echo $jsonObjet->results[$i]->name ?></h6>
					</span>
					<p><h8><?php echo substr($jsonObjet->results[$i]->created,0,10); ?></h8></p>
				</div>
			</div>
			<?php
			echo "</div>";
	}

	if ($c == $cont && $print ==0){
			$c = 0;
			$print = 1;
			echo "<div class=\"col s".$sNum." center\">";
			?>
			<div class="card blue-grey darken-1">
				<div class="card-image">
					<img src="<?php echo $jsonObjet->results[$i]->image ?>" alt="" class="responsive-img imgStyl">
				</div>
				<div class="card-content white-text">
					<span class="card-title flow-text">
						<h6><?php echo $jsonObjet->results[$i]->name ?></h6>
					</span>
					<p><h8><?php echo substr($jsonObjet->results[$i]->created,0,10); ?></h8></p>
				</div>
			</div>
			<?php
			echo "</div>";
			echo "</div>";
	}
} ?>

<div class="divider"></div>

<div class="row">
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1 center">
		<?php echo Phalcon\Tag::linkTo(array($linkLeft, 'keyboard_arrow_left', 'class' => 'material-icons'));?>
	</div>
	<div class="col s2 center">
		<?php echo $paginaActual;?>
	</div>
	<div class="col s1 center">
		<?php echo Phalcon\Tag::linkTo(array($linkRight, 'keyboard_arrow_right', 'class' => 'material-icons'));?>
	</div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
	<div class="col s1"></div>
</div>


