<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Prueba de Habilidad</title>
        <!-- CSS -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.teal-red.min.css">
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
        <style type="text/css" media="screen">
            .mdl-button {
                margin-top: 10px;
                margin-bottom: 10px;
                margin-right: 10px;
            }
            
            .imgStyl {
                display: flex;
                -webkit-box-pack: center;
                justify-content: center;
                -webkit-box-align: center;
                align-items: center;
                min-height: calc(50vh - 60px);
                padding: 1rem 0px;
                background: rgb(32, 35, 41);
            }
        </style>
        <!-- SCRIPTS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
        <script src="https://storage.googleapis.com/code.getmdl.io/1.0.1/material.min.js"></script>


    </head>
    <body>
        <div class="container">
            <?php echo $this->getContent(); ?>
            <footer class="card-panel teal lighten-2 z-depth-2">
                <div class="footer-copyright">
                    © 2020 Copyright Prueba de Habilidad
                </div>
            </footer>
        </div>
    </body>
</html>
